version: 1.2
workflows:
- name: QcPlots
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/QcPlots.wdl
  testParameterFiles:
- name: PlotHwe
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHwe.wdl
  testParameterFiles:
- name: PlotHweImpl
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweImpl.wdl
  testParameterFiles:
- name: PlotHweFocused
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweFocused.wdl
  testParameterFiles:
- name: PlotHweFocusedAc
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweFocusedAc.wdl
  testParameterFiles:
- name: PlotHweFocusedTruvariCollapse
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PlotHweFocusedTruvariCollapse.wdl
  testParameterFiles:
- name: TRGTMergeCohort
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/TRGTMergeCohort.wdl
  testParameterFiles:
- name: UltralongAnnotate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongAnnotate.wdl
  testParameterFiles:
- name: UltralongCanonizeDipcall
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongCanonizeDipcall.wdl
  testParameterFiles:
- name: UltralongGetTrainingIntervals
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongGetTrainingIntervals.wdl
  testParameterFiles:
- name: UltralongGetTrainingIntervalsSvim
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongGetTrainingIntervalsSvim.wdl
  testParameterFiles:
- name: UltralongMerge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongMerge.wdl
  testParameterFiles:
- name: UltralongRecordsInTrack
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongRecordsInTrack.wdl
  testParameterFiles:
- name: UltralongScore
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/UltralongScore.wdl
  testParameterFiles:
- name: SV_Integration_BndAnnotate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_BndAnnotate.wdl
  testParameterFiles:
- name: SV_Integration_BndGetTrainingIntervals
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_BndGetTrainingIntervals.wdl
  testParameterFiles:
- name: SV_Integration_BuildTrainingResource
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_BuildTrainingResource.wdl
  testParameterFiles:
- name: SV_Integration_PlotHwe
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_PlotHwe.wdl
  testParameterFiles:
- name: SV_Integration_PlotHwe_SNVs
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_PlotHwe_SNVs.wdl
  testParameterFiles:
- name: SV_Integration_PlotPrme
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_PlotPrme.wdl
  testParameterFiles:
- name: SV_Integration_RegenotypingAnalysis
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_RegenotypingAnalysis.wdl
  testParameterFiles:
- name: SV_Integration_UltralongAnalysis
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_UltralongAnalysis.wdl
  testParameterFiles:
- name: SV_Integration_UltralongAnnotate
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_UltralongAnnotate.wdl
  testParameterFiles:
- name: SV_Integration_UltralongGetTrainingIntervals
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_UltralongGetTrainingIntervals.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage1_ExtractUltralongBnd2kb
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage1_ExtractUltralongBnd2kb.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage1_intrasample_merge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage1_intrasample_merge.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage2_Main_scoring
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage2_Main_scoring.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage3_Main_bcftools_merge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage3_Main_bcftools_merge.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage4_Main_shard
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage4_Main_shard.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage5_Bnd
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage5_Bnd.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage5_Main_truvari_collapse
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage5_Main_truvari_collapse.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage6_Main_concat_shards
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage6_Main_concat_shards.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage7_Main_joint_genotype_families
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage7_Main_joint_genotype_families.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage7_trios
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage7_trios.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage8_Main_concat_regenotyped_shards
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage8_Main_concat_regenotyped_shards.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage9
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage9.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage12
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage12.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage13
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage13.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage14
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage14.wdl
  testParameterFiles:
- name: SV_Integration_Workpackage15
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/SV_Integration_Workpackage15.wdl
  testParameterFiles:
- name: PAV_BcftoolsMerge_1_Split
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV_BcftoolsMerge_1_Split.wdl
  testParameterFiles:
- name: PAV_BcftoolsMerge_2_Merge
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV_BcftoolsMerge_2_Merge.wdl
  testParameterFiles:
- name: PAV_BcftoolsMerge_3_Concat
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV_BcftoolsMerge_3_Concat.wdl
  testParameterFiles:
- name: PAV_BcftoolsMerge_Orchestrator
  subclass: wdl
  publish: True
  primaryDescriptorPath: /wdl/PAV_BcftoolsMerge_Orchestrator.wdl
  testParameterFiles:
